# Generated by Django 5.2.4 on 2025-11-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='name',
            field=models.CharField(default='Your name', max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='Write Message...'),
        ),
    ]
