# Generated by Django 5.2.4 on 2025-11-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your name', max_length=100)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=100)),
                ('phone', models.CharField(default='1234567890', max_length=20)),
                ('people', models.IntegerField(choices=[(1, '1 Person'), (2, '2 People'), (3, '3 People'), (4, '4 People'), (5, '5 People'), (6, '6 People or More')], default=1)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('message', models.TextField(default='Write Message...')),
            ],
        ),
    ]
