# Generated by Django 5.2.4 on 2025-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='people',
            field=models.IntegerField(default='Number People'),
        ),
    ]
