# Generated by Django 5.2.4 on 2025-11-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0002_alter_booktable_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(default='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.DateTimeField(default='Bookign Time'),
        ),
    ]
