# Generated by Django 5.2.4 on 2025-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0003_alter_booktable_date_alter_booktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='people',
            field=models.CharField(default='Number People'),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
