# Generated by Django 5.2.4 on 2025-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0004_alter_booktable_date_alter_booktable_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.TimeField(),
        ),
    ]
